In [23]:
import pandas as pd
import numpy as np

In [24]:
df = pd.read_excel("olympic_medals.xlsx", index_col=0)

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 21697 entries, 0 to 21696
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   discipline_title       21697 non-null  object
 1   slug_game              21697 non-null  object
 2   event_title            21697 non-null  object
 3   event_gender           21697 non-null  object
 4   medal_type             21697 non-null  object
 5   participant_type       21697 non-null  object
 6   participant_title      6584 non-null   object
 7   athlete_url            17027 non-null  object
 8   athlete_full_name      18073 non-null  object
 9   country_name           21697 non-null  object
 10  country_code           20195 non-null  object
 11  country_3_letter_code  21697 non-null  object
dtypes: object(12)
memory usage: 2.2+ MB

In [26]:
# Valeurs nulles
df.isnull().sum()

discipline_title             0
slug_game                    0
event_title                  0
event_gender                 0
medal_type                   0
participant_type             0
participant_title        15113
athlete_url               4670
athlete_full_name         3624
country_name                 0
country_code              1502
country_3_letter_code        0
dtype: int64

In [27]:
# remove useless columns
df = df.drop(columns=['participant_title', 'athlete_url', 'country_code'])
df.columns

Index(['discipline_title', 'slug_game', 'event_title', 'event_gender',
       'medal_type', 'participant_type', 'athlete_full_name', 'country_name',
       'country_3_letter_code'],
      dtype='object')

In [28]:
# Visualiser les doublons
duplicates = df.duplicated()
df[duplicates]
# Il n'y a pas de doublons

,discipline_title,slug_game,event_title,event_gender,medal_type,participant_type,athlete_full_name,country_name,country_3_letter_code
20583,Rowing,stockholm-1912,four-oared shell with coxswain men,Men,SILVER,GameTeam,NaN,Great Britain,GBR
20911,Polo,london-1908,polo men,Men,SILVER,GameTeam,NaN,Great Britain,GBR
20960,Hockey,london-1908,hockey men,Men,BRONZE,GameTeam,NaN,Great Britain,GBR
21570,Polo,paris-1900,polo men,Men,BRONZE,GameTeam,NaN,MIX,MIX

In [29]:
# Enlever les éditions d'hiver
# info : finalement on le fera en pré-traitement, pas dans le nettoyage

df['slug_game'].unique()

# winter_games = [
#     'beijing-2022', 'pyeongchang-2018', 'sochi-2014', 'vancouver-2010', 
#     'turin-2006', 'salt-lake-city-2002', 'nagano-1998', 'lillehammer-1994', 
#     'albertville-1992', 'calgary-1988', 'sarajevo-1984', 'lake-placid-1980', 
#     'innsbruck-1976', 'sapporo-1972', 'grenoble-1968', 'innsbruck-1964', 
#     'squaw-valley-1960', 'cortina-d-ampezzo-1956', 'oslo-1952', 
#     'st-moritz-1948', 'garmisch-partenkirchen-1936', 'lake-placid-1932', 
#     'st-moritz-1928', 'chamonix-1924'
# ]

# Les éditions qui ne sont pas dans les jeux d'hiver
# summer_games = df[~df['slug_game'].isin(winter_games)]
# summer_games

array(['beijing-2022', 'tokyo-2020', 'pyeongchang-2018', 'rio-2016',
       'sochi-2014', 'london-2012', 'vancouver-2010', 'beijing-2008',
       'turin-2006', 'athens-2004', 'salt-lake-city-2002', 'sydney-2000',
       'nagano-1998', 'atlanta-1996', 'lillehammer-1994',
       'barcelona-1992', 'albertville-1992', 'seoul-1988', 'calgary-1988',
       'los-angeles-1984', 'sarajevo-1984', 'moscow-1980',
       'lake-placid-1980', 'montreal-1976', 'innsbruck-1976',
       'munich-1972', 'sapporo-1972', 'mexico-city-1968', 'grenoble-1968',
       'tokyo-1964', 'innsbruck-1964', 'rome-1960', 'squaw-valley-1960',
       'melbourne-1956', 'cortina-d-ampezzo-1956', 'helsinki-1952',
       'oslo-1952', 'london-1948', 'st-moritz-1948', 'berlin-1936',
       'garmisch-partenkirchen-1936', 'los-angeles-1932',
       'lake-placid-1932', 'amsterdam-1928', 'st-moritz-1928',
       'paris-1924', 'chamonix-1924', 'antwerp-1920', 'stockholm-1912',
       'london-1908', 'st-louis-1904', 'paris-1900', 'athens-1896'],
      dtype=object)

In [30]:
# Filter les données à partir de 2000

# Création d'une colonne year en se basant sur la colonne slug_game
df['year'] = df['slug_game'].str.extract(r'(\d{4})').astype(int)
del df['slug_game']

In [31]:
df = df[df['year'] >= 2000]
df

,discipline_title,event_title,event_gender,medal_type,participant_type,athlete_full_name,country_name,country_3_letter_code,year
0,Curling,Mixed Doubles,Mixed,GOLD,GameTeam,Stefania CONSTANTINI,Italy,ITA,2022
1,Curling,Mixed Doubles,Mixed,GOLD,GameTeam,Amos MOSANER,Italy,ITA,2022
2,Curling,Mixed Doubles,Mixed,SILVER,GameTeam,Kristin SKASLIEN,Norway,NOR,2022
3,Curling,Mixed Doubles,Mixed,SILVER,GameTeam,Magnus NEDREGOTTEN,Norway,NOR,2022
4,Curling,Mixed Doubles,Mixed,BRONZE,GameTeam,Almida DE VAL,Sweden,SWE,2022
...,...,...,...,...,...,...,...,...,...
8183,Taekwondo,57 - 67 kg women,Women,SILVER,Athlete,Trude GUNDERSEN,Norway,NOR,2000
8184,Taekwondo,57 - 67 kg women,Women,BRONZE,Athlete,Yoriko OKAMOTO,Japan,JPN,2000
8185,Taekwondo,49 kg women,Women,GOLD,Athlete,Lauren BURNS,Australia,AUS,2000
8186,Taekwondo,49 kg women,Women,SILVER,Athlete,Urbia MELENDEZ RODRIGUEZ,Cuba,CUB,2000
8187,Taekwondo,49 kg women,Women,BRONZE,Athlete,Shu Ju CHI,Chinese Taipei,TPE,2000

In [32]:
# Supprimer les disciplines qui ne sont pas dans la prochaine édition
# info : finalement on le fera en pré-traitement, pas dans le nettoyage


# Trouver les disciplines unique tous JO confondus
# disciplines = df['discipline_title'].unique()
# disciplines

# Seules ces discplines sont présentes dans l'édition 2024
# disciplines_2024 = ['Figure skating',
#        'Shooting', 'Diving', 'Canoe Sprint', 'Cycling Road', 'Football', 'Boxing',
#        'Artistic Swimming', 'Handball', 'Rugby Sevens',
#        'Cycling BMX Racing', 'Triathlon', 'Surfing', 'Table Tennis',
#        'Canoe Slalom', 'Marathon Swimming', 'Trampoline Gymnastics',
#        'Volleyball', 'Basketball', 'Taekwondo', 'Cycling Track',
#        'Fencing', 'Badminton', 'Water Polo', 'Sport Climbing',
#        'Wrestling', 'Tennis', 'Artistic Gymnastics', 'Golf',
#        'Cycling BMX Freestyle', 'Judo', 'Skateboarding', 'Archery',
#        'Weightlifting',
#        'Modern Pentathlon', 'Athletics', 'Swimming', 'Sailing',
#        'Cycling Mountain Bike', 'Rowing', '3x3 Basketball',
#        'Rhythmic Gymnastics', 'Hockey', 'Beach Volleyball',
#        'Cycling BMX', 'Rugby', 'Gymnastics Rhythmic', 'Gymnastics Artistic',
#        'Synchronized Swimming', 'Trampoline'
#     ]

# Ne garder que les données en rapport avec ces disciplines
# df = df[df['discipline_title'].isin(disciplines_2024)]
# df

df['discipline_title'].unique()

array(['Curling', 'Freestyle Skiing', 'Short Track Speed Skating',
       'Snowboard', 'Ski Jumping', 'Figure skating', 'Luge', 'Ice Hockey',
       'Biathlon', 'Alpine Skiing', 'Skeleton', 'Cross Country Skiing',
       'Speed skating', 'Nordic Combined', 'Bobsleigh', 'Shooting',
       'Diving', 'Canoe Sprint', 'Cycling Road', 'Football', 'Boxing',
       'Artistic Swimming', 'Handball', 'Rugby Sevens',
       'Cycling BMX Racing', 'Triathlon', 'Surfing', 'Table Tennis',
       'Canoe Slalom', 'Marathon Swimming', 'Trampoline Gymnastics',
       'Volleyball', 'Basketball', 'Taekwondo', 'Cycling Track',
       'Fencing', 'Badminton', 'Water Polo', 'Sport Climbing',
       'Wrestling', 'Tennis', 'Artistic Gymnastics', 'Golf',
       'Cycling BMX Freestyle', 'Judo', 'Skateboarding', 'Archery',
       'Weightlifting', 'Baseball/Softball', 'Equestrian',
       'Modern Pentathlon', 'Athletics', 'Swimming', 'Sailing',
       'Cycling Mountain Bike', 'Rowing', 'Karate', '3x3 Basketball',
       'Rhythmic Gymnastics', 'Hockey', 'Beach Volleyball', 'Short Track',
       'Cycling BMX', 'Rugby', 'Gymnastics Rhythmic',
       'Equestrian Jumping', 'Gymnastics Artistic',
       'Synchronized Swimming', 'Trampoline', 'Equestrian Eventing',
       'Equestrian Dressage', 'Baseball', 'Softball'], dtype=object)

In [33]:
# Rassembler Gymnastics Rhythmic et Rhythmic Gymnastics dans une même colonne
df.loc[:,'discipline_title'] = df['discipline_title'].replace('Gymnastics Rhythmic', 'Rhythmic Gymnastics')

# Rassembler Artistic Gymnastics et Gymnastics Artistic dans une même colonne
df.loc[:,'discipline_title'] = df['discipline_title'].replace('Artistic Gymnastics', 'Gymnastics Artistic')

In [34]:
df[df['discipline_title'] == 'Artistic Gymnastics'] # 0 left
df[df['discipline_title'] == 'Gymnastics Artistic']

df[df['discipline_title'] == 'Gymnastics Rhythmic'] # 0 left
df[df['discipline_title'] == 'Rhythmic Gymnastics']

,discipline_title,event_title,event_gender,medal_type,participant_type,athlete_full_name,country_name,country_3_letter_code,year
1519,Rhythmic Gymnastics,Individual All-Around,Women,SILVER,Athlete,Dina AVERINA,ROC,ROC,2020
1520,Rhythmic Gymnastics,Individual All-Around,Women,BRONZE,Athlete,Alina HARNASKO,Belarus,BLR,2020
1521,Rhythmic Gymnastics,Individual All-Around,Women,GOLD,Athlete,Linoy ASHRAM,Israel,ISR,2020
1522,Rhythmic Gymnastics,Group All-Around,Women,GOLD,GameTeam,NaN,Bulgaria,BUL,2020
1523,Rhythmic Gymnastics,Group All-Around,Women,SILVER,GameTeam,NaN,ROC,ROC,2020
1524,Rhythmic Gymnastics,Group All-Around,Women,BRONZE,GameTeam,NaN,Italy,ITA,2020
1898,Rhythmic Gymnastics,Group All-Around women,Women,GOLD,GameTeam,NaN,Russian Federation,RUS,2016
1899,Rhythmic Gymnastics,Group All-Around women,Women,SILVER,GameTeam,NaN,Spain,ESP,2016
1900,Rhythmic Gymnastics,Group All-Around women,Women,BRONZE,GameTeam,NaN,Bulgaria,BUL,2016
1901,Rhythmic Gymnastics,Individual All-Around women,Women,GOLD,Athlete,Margarita MAMUN,Russian Federation,RUS,2016
1902,Rhythmic Gymnastics,Individual All-Around women,Women,SILVER,Athlete,Yana KUDRYAVTSEVA,Russian Federation,RUS,2016
1903,Rhythmic Gymnastics,Individual All-Around women,Women,BRONZE,Athlete,Ganna RIZATDINOVA,Ukraine,UKR,2016
4199,Rhythmic Gymnastics,group competition women,Women,GOLD,GameTeam,NaN,Russian Federation,RUS,2012
4200,Rhythmic Gymnastics,group competition women,Women,SILVER,GameTeam,NaN,Belarus,BLR,2012
4201,Rhythmic Gymnastics,group competition women,Women,BRONZE,GameTeam,NaN,Italy,ITA,2012
4202,Rhythmic Gymnastics,individual all-round women,Women,GOLD,Athlete,Yevgeniya Kanayeva,Russian Federation,RUS,2012
4203,Rhythmic Gymnastics,individual all-round women,Women,SILVER,Athlete,Darya Dmitriyeva,Russian Federation,RUS,2012
4204,Rhythmic Gymnastics,individual all-round women,Women,BRONZE,Athlete,Lyubov CHERKASHINA,Belarus,BLR,2012
5334,Rhythmic Gymnastics,group competition women,Women,GOLD,GameTeam,NaN,Russian Federation,RUS,2008
5335,Rhythmic Gymnastics,group competition women,Women,SILVER,GameTeam,NaN,People's Republic of China,CHN,2008
5336,Rhythmic Gymnastics,group competition women,Women,BRONZE,GameTeam,NaN,Belarus,BLR,2008
5337,Rhythmic Gymnastics,individual all-round women,Women,GOLD,Athlete,Yevgeniya Kanayeva,Russian Federation,RUS,2008
5338,Rhythmic Gymnastics,individual all-round women,Women,SILVER,Athlete,Inna ZHUKOVA,Belarus,BLR,2008
5339,Rhythmic Gymnastics,individual all-round women,Women,BRONZE,Athlete,Hanna Bezsonova,Ukraine,UKR,2008
6426,Rhythmic Gymnastics,individual all-round women,Women,GOLD,Athlete,Alina KABAEVA,Russian Federation,RUS,2004
6427,Rhythmic Gymnastics,individual all-round women,Women,SILVER,Athlete,Irina TCHACHINA,Russian Federation,RUS,2004
6428,Rhythmic Gymnastics,individual all-round women,Women,BRONZE,Athlete,Hanna Bezsonova,Ukraine,UKR,2004
6429,Rhythmic Gymnastics,group competition women,Women,GOLD,GameTeam,NaN,Russian Federation,RUS,2004
6430,Rhythmic Gymnastics,group competition women,Women,SILVER,GameTeam,NaN,Italy,ITA,2004
6431,Rhythmic Gymnastics,group competition women,Women,BRONZE,GameTeam,NaN,Bulgaria,BUL,2004
7677,Rhythmic Gymnastics,individual all-round women,Women,GOLD,Athlete,Yuliya Barsukova,Russian Federation,RUS,2000
7678,Rhythmic Gymnastics,individual all-round women,Women,SILVER,Athlete,Yulia RASKINA,Belarus,BLR,2000
7679,Rhythmic Gymnastics,individual all-round women,Women,BRONZE,Athlete,Alina KABAEVA,Russian Federation,RUS,2000
7680,Rhythmic Gymnastics,group competition women,Women,GOLD,GameTeam,NaN,Russian Federation,RUS,2000
7681,Rhythmic Gymnastics,group competition women,Women,SILVER,GameTeam,NaN,Belarus,BLR,2000
7682,Rhythmic Gymnastics,group competition women,Women,BRONZE,GameTeam,NaN,Greece,GRE,2000

In [35]:
# On vérifie qu'il ne reste aucune valeurs nulles dans le dataset
df.isnull().sum()

discipline_title            0
event_title                 0
event_gender                0
medal_type                  0
participant_type            0
athlete_full_name        1223
country_name                0
country_3_letter_code       0
year                        0
dtype: int64

In [36]:
df['participant_type'].unique()
# df['event_title'].unique()

array(['GameTeam', 'Athlete'], dtype=object)

In [37]:
# Rename "country_3_letter_code" column to "country code"
df.rename(columns={'country_3_letter_code': 'country_code'}, inplace=True)
df

,discipline_title,event_title,event_gender,medal_type,participant_type,athlete_full_name,country_name,country_code,year
0,Curling,Mixed Doubles,Mixed,GOLD,GameTeam,Stefania CONSTANTINI,Italy,ITA,2022
1,Curling,Mixed Doubles,Mixed,GOLD,GameTeam,Amos MOSANER,Italy,ITA,2022
2,Curling,Mixed Doubles,Mixed,SILVER,GameTeam,Kristin SKASLIEN,Norway,NOR,2022
3,Curling,Mixed Doubles,Mixed,SILVER,GameTeam,Magnus NEDREGOTTEN,Norway,NOR,2022
4,Curling,Mixed Doubles,Mixed,BRONZE,GameTeam,Almida DE VAL,Sweden,SWE,2022
...,...,...,...,...,...,...,...,...,...
8183,Taekwondo,57 - 67 kg women,Women,SILVER,Athlete,Trude GUNDERSEN,Norway,NOR,2000
8184,Taekwondo,57 - 67 kg women,Women,BRONZE,Athlete,Yoriko OKAMOTO,Japan,JPN,2000
8185,Taekwondo,49 kg women,Women,GOLD,Athlete,Lauren BURNS,Australia,AUS,2000
8186,Taekwondo,49 kg women,Women,SILVER,Athlete,Urbia MELENDEZ RODRIGUEZ,Cuba,CUB,2000
8187,Taekwondo,49 kg women,Women,BRONZE,Athlete,Shu Ju CHI,Chinese Taipei,TPE,2000

In [38]:
# Vérifier s'il reste des valeurs nulles
df.isnull().sum()

discipline_title        0
event_title             0
event_gender            0
medal_type              0
participant_type        0
athlete_full_name    1223
country_name            0
country_code            0
year                    0
dtype: int64

In [39]:
# Enregistrer le dataframe dans un nouveau fichier csv
df.to_csv('filtered_data.csv', index=False)

df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8188 entries, 0 to 8187
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   discipline_title   8188 non-null   object
 1   event_title        8188 non-null   object
 2   event_gender       8188 non-null   object
 3   medal_type         8188 non-null   object
 4   participant_type   8188 non-null   object
 5   athlete_full_name  6965 non-null   object
 6   country_name       8188 non-null   object
 7   country_code       8188 non-null   object
 8   year               8188 non-null   int32
dtypes: int32(1), object(8)
memory usage: 607.7+ KB

In [40]:
# Insérer le dataset nettoyé en base de données

from sqlalchemy import create_engine

username = 'jo2024_fatima'
password = 'Ipssi2024!'
hostname = 'postgresql-jo2024.alwaysdata.net'
database = 'jo2024_postgres'

connection_url = f'postgresql://{username}:{password}@{hostname}:5432/{database}'

engine = create_engine(connection_url)

table_name = 'olympic_medals'

df.to_sql(table_name, con=engine, if_exists='append', index=False)

188